# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='unidad_de_repeticion',
            field=models.IntegerField(blank=True, choices=[(3, 'Mes(es)'), (4, 'A\xf1o(s)'), (5, 'Hora(s)')], default=3, null=True),
        ),
    ]
