# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='operario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Operario'),
            preserve_default=False,
        ),
    ]
