# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0003_auto_20160904_1349'),
        ('formulario', '0002_registro_operario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='equipo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='operacion.Equipo'),
            preserve_default=False,
        ),
    ]
