# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=400)),
                ('repetir_cada', models.TextField(default=0)),
                ('unidad_de_repeticion', models.IntegerField(blank=True, choices=[(3, 'Mes(es)'), (4, 'A\xf1o(s)')], default=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('abreviatura', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Ciudad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Planta')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('valor_min', models.IntegerField(verbose_name='Valor minimo')),
                ('valor_med', models.IntegerField(verbose_name='Valor medio')),
                ('valor_max', models.IntegerField(verbose_name='Valor maximo')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Equipo')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Medida')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Turno'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.Unidad'),
        ),
    ]
