# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='repetir_cada',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='unidad_de_repeticion',
        ),
        migrations.DeleteModel(
            name='Medida',
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
