# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0002_auto_20160903_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
    ]
