# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0003_auto_20160904_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='hora_inicio',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
